[package]
name = "lume_parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
lume_errors = { workspace = true }
lume_lexer = { workspace = true }
lume_span = { workspace = true }
lume_syntax = { workspace = true }

tracing = { workspace = true }

[dev-dependencies]
insta = { version = "1.42.2" }

[lints]
workspace = true
