[package]
name = "lume_errors"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
indexmap = { workspace = true }
owo-colors = { workspace = true, features = ["supports-colors"] }
terminal_size = { version = "^0.4", optional = true }

[lints]
workspace = true
