[package]
name = "lume_driver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
arc = { workspace = true }
lume_errors = { workspace = true }
lume_hir = { workspace = true }
lume_hir_lower = { workspace = true }
lume_infer = { workspace = true }
lume_linker = { workspace = true }
lume_metadata = { workspace = true }
lume_mir = { workspace = true }
lume_mir_lower = { workspace = true }
lume_mir_opt = { workspace = true }
lume_session = { workspace = true }
lume_span = { workspace = true }
lume_tir = { workspace = true }
lume_tir_lower = { workspace = true }
lume_typech = { workspace = true }
lume_types = { workspace = true }
lume_unification = { workspace = true }

ciborium = { version = "=0.2.2" }
indexmap = { workspace = true }
tracing = { workspace = true }

lume_codegen = { workspace = true, optional = true }

[dev-dependencies]
lume_errors_test = { workspace = true }

[features]
default = ["codegen", "test-support"]
codegen = ["dep:lume_codegen"]
test-support = ["codegen"]

[lints]
workspace = true
