[package]
name = "manifold"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
build_stage = { workspace = true }
lume_driver = { workspace = true, features = ["test-support"] }
lume_errors = { workspace = true }
lume_gc = { workspace = true, features = ["paranoid"] }
lume_span = { workspace = true }

clap = { workspace = true }
error_snippet = { workspace = true }
glob = "^0"
owo-colors = { workspace = true }
rayon = "=1.11.0"
regex = { workspace = true }
similar = { version = "=2.7.0", features = ["inline"] }

[dev-dependencies]
manifold_macros = { path = "../manifold_macros" }

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["lume_gc"]
