[package]
name = "lume_lexer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
lume_errors = { workspace = true }
lume_errors_derive = { workspace = true }
lume_span = { workspace = true }

logos = { version = "=0.15.1" }

[lints]
workspace = true
