[package]
name = "lume"
version = { workspace = true }
rust-version = { workspace = true }
edition = { workspace = true }
default-run = "lume"

[workspace]
members = ["compiler/lume_cli", "crates/*", "tools/bootstrap", "tools/manifold", "tools/grammar", "fuzz", "rt/lume_runtime"]
resolver = "3"

[[bin]]
name = "lume"
path = "src/lume.rs"
test = false

[[bin]]
name = "lume-bootstrap"
path = "src/lume-bootstrap.rs"
test = false

[workspace.package]
version = "0.1.3"
rust-version = "1.92.0"
edition = "2024"
authors = ["Max T. Kristiansen <me@maxtrier.dk>"]
license = "MIT"

[workspace.dependencies]
# Compiler packages
arc = { path = "compiler/arc" }
lume_ast = { path = "compiler/lume_ast" }
lume_assets = { path = "crates/lume_assets" }
lume_cli = { path = "compiler/lume_cli" }
lume_cli_tools = { path = "crates/lume_cli_tools" }
lume_codegen = { path = "compiler/lume_codegen" }
lume_demangle = { path = "crates/lume_demangle" }
lume_driver = { path = "compiler/lume_driver", default-features = false }
lume_errors = { path = "crates/lume_errors" }
lume_errors_derive = { path = "crates/lume_errors_derive" }
lume_errors_test = { path = "crates/lume_errors_test" }
lume_hash = { path = "crates/lume_hash" }
lume_hir = { path = "compiler/lume_hir" }
lume_hir_lower = { path = "compiler/lume_hir_lower" }
lume_infer = { path = "compiler/lume_infer" }
lume_lexer = { path = "compiler/lume_lexer" }
lume_linker = { path = "compiler/lume_linker" }
lume_lsp = { path = "compiler/lume_lsp" }
lume_macros = { path = "crates/lume_macros" }
lume_mangle = { path = "crates/lume_mangle" }
lume_metadata = { path = "crates/lume_metadata" }
lume_mir = { path = "compiler/lume_mir" }
lume_mir_lower = { path = "compiler/lume_mir_lower" }
lume_mir_opt = { path = "compiler/lume_mir_opt" }
lume_mir_queries = { path = "compiler/lume_mir_queries" }
lume_parser = { path = "compiler/lume_parser" }
lume_session = { path = "compiler/lume_session" }
lume_signals = { path = "crates/lume_signals" }
lume_span = { path = "crates/lume_span" }
lume_syntax = { path = "crates/lume_syntax" }
lume_tir = { path = "compiler/lume_tir" }
lume_tir_lower = { path = "compiler/lume_tir_lower" }
lume_tracing = { path = "crates/lume_tracing" }
lume_type_metadata = { path = "compiler/lume_type_metadata" }
lume_typech = { path = "compiler/lume_typech" }
lume_types = { path = "compiler/lume_types" }
lume_unification = { path = "compiler/lume_unification" }

# Compiler tool packages
bootstrap = { path = "tools/bootstrap" }
build_stage = { path = "tools/build_stage" }
lume_benchmark = { path = "tools/benchmark" }
lume_benchmark_macros = { path = "tools/benchmark_macros" }
lume_fmt = { path = "tools/fmt" }
grammar = { path = "tools/grammar" }
manifold = { path = "tools/manifold" }
manifold_macros = { path = "tools/manifold_macros" }

# Runtime packages
lume_gc = { path = "rt/lume_gc" }
lume_options = { path = "rt/lume_options" }
lume_rt_macros = { path = "rt/lume_rt_macros" }
lume_rt_metadata = { path = "rt/lume_rt_metadata" }
lume_runtime = { path = "rt/lume_runtime" }
lume_tagged = { path = "rt/lume_tagged" }

# 3rd-party packages
clap = { version = "=4.5.39", features = ["derive"] }
indexmap = { version = "=2.11.3" }
lume_architect = { git = "https://github.com/lume-lang/architect" }
owo-colors = { version = "=4.2.2" }
regex = { version = "=1.11.1" }
semver = { version = "^1", features = ["serde"] }
serde = { version = "^1.0.228", features = ["derive"] }
serde_json = { version = "^1.0.140" }
tracing = { version = "0.1.44", features = ["max_level_trace", "release_max_level_off"] }

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
must_use_candidate = "allow"
wildcard_imports = "allow"
range_plus_one = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
missing_safety_doc = "allow"
return_self_not_must_use = "allow"
wrong_self_convention = "allow"
needless_pass_by_value = "allow"
redundant_closure_for_method_calls = "allow"
similar-names = "allow"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fuzzing)'] }

[dependencies]
bootstrap = { workspace = true }
lume_cli = { workspace = true }
lume_driver = { workspace = true }

[dev-dependencies]
lume_benchmark = { workspace = true }
lume_errors = { workspace = true }

criterion = { version = "0.8.1", features = ["html_reports"] }

[profile.profiling]
inherits = "release"
debug = true

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[lints]
workspace = true
