[package]
name = "lume_mir_opt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
lume_mir = { workspace = true }
lume_mir_queries = { workspace = true }
lume_session = { workspace = true }
lume_span = { workspace = true }
lume_typech = { workspace = true }

tracing = { workspace = true }

[lints]
workspace = true
