[package]
name = "lume_fmt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lib]
doctest = false

[dependencies]
lume_ast = { workspace = true }
lume_errors = { workspace = true }
lume_lexer = { workspace = true }
lume_span = { workspace = true }
lume_parser = { workspace = true }

im = { version = "15.1.0" }
iter_tools = { version = "0.43.0" }
serde = { workspace = true, features = ["derive"] }

[lints]
workspace = true
