[package]
name = "build_stage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
test = false
doctest = false

[dependencies]
arc = { workspace = true }
lume_codegen = { workspace = true }
lume_errors = { workspace = true }
lume_hir = { workspace = true }
lume_hir_lower = { workspace = true }
lume_infer = { workspace = true }
lume_linker = { workspace = true }
lume_mir = { workspace = true }
lume_mir_lower = { workspace = true }
lume_session = { workspace = true }
lume_span = { workspace = true }
lume_tir = { workspace = true }
lume_tir_lower = { workspace = true }
lume_typech = { workspace = true }
lume_types = { workspace = true }
lume_unification = { workspace = true }

[lints]
workspace = true
