[package]
name = "lume_benchmark"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lib]
doctest = false

[dependencies]
divan = { version = "0.1.21" }
proc-macro2 = {version = "1" }
quote = { version = "1.0.44" }

lume_benchmark_macros = { workspace = true }
lume_driver = { workspace = true, features = ["test-support"] }
lume_errors = { workspace = true }
lume_session = { workspace = true }

[lints]
workspace = true
