[package]
name = "lume_benchmark_macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
test = false
doctest = false

proc-macro = true

[dependencies]
darling = { version = "0.21.3" }
proc-macro2 = "1"
quote = "1"
syn = { version = "2.0.9", features = ["full"] }

[lints]
workspace = true
