[package]
name = "lume_tir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
test = false
doctest = false

[dependencies]
indexmap = { workspace = true }

lume_errors = { workspace = true }
lume_span = { workspace = true }
lume_type_metadata = { workspace = true }
lume_types = { workspace = true }

[lints]
workspace = true
