[package]
name = "bootstrap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
lume_assets = { workspace = true }
lume_cli_tools = { workspace = true }
lume_errors = { workspace = true }

clap = { workspace = true }
owo-colors = { workspace = true }
regex = { workspace = true }
ureq = { version = "3.2.0", features = ["json"] }
semver = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
trycmd = { version = "=0.15.11" }

[lints]
workspace = true
