[package]
name = "lume_span"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
lume_errors = { workspace = true }
lume_errors_derive = { workspace = true }
lume_hash = { workspace = true }

indexmap = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive", "rc"] }

[lints]
workspace = true
