[package]
name = "lume-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
afl = "*"
libfuzzer-sys = "0.4"

lume_driver = { workspace = true, features = ["test-support"] }
lume_errors = { path = "../crates/lume_errors" }
lume_lexer = { path = "../compiler/lume_lexer" }
lume_parser = { path = "../compiler/lume_parser" }
lume_span = { path = "../crates/lume_span" }

[lints]
workspace = true

[[bin]]
name = "fuzz-lexer"
path = "fuzz_targets/lume_lexer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz-parser"
path = "fuzz_targets/lume_parser.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz-parser-expr"
path = "fuzz_targets/lume_parser_expr.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz-compiler"
path = "fuzz_targets/lume_mutation.rs"
test = false
doc = false
bench = false
