[package]
name = "lume_runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false
crate-type = ["lib", "staticlib"]

[dependencies]
backtrace = { version = "=0.3.76" }
lume_gc = { workspace = true }
lume_options = { workspace = true }
lume_rt_metadata = { workspace = true }
lume_signals = { workspace = true }
lume_tagged = { workspace = true }

owo-colors = { version = "4.2", optional = true, features = ["supports-colors"] }

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
must_use_candidate = "allow"
wildcard_imports = "allow"
range_plus_one = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
missing_safety_doc = "allow"
disallowed_macros = "allow"

[features]
default = ["color"]
color = ["dep:owo-colors"]
