[package]
name = "lume_hir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
lume_ast = { workspace = true }
lume_errors = { workspace = true }
lume_macros = { workspace = true }
lume_span = { workspace = true }

error_snippet = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
insta = { version = "1.42.2", features = ["yaml"] }

[lints]
workspace = true
