[package]
name = "lume_ast"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
lume_span = { workspace = true }
lume_syntax = { workspace = true }

[dev-dependencies]
lume_parser = { workspace = true }

insta = { version = "1.42.2", features = ["yaml"] }

[lints]
workspace = true
