[package]
name = "lume_gc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
lume_options = { workspace = true }
lume_rt_macros = { workspace = true }
lume_rt_metadata = { workspace = true }
lume_tagged = { workspace = true }

indexmap = { workspace = true }
mimalloc = { version = "=0.1.48" }
sysinfo = { version = "=0.37.0" }
tracing = { workspace = true }

[dev-dependencies]
lume_benchmark = { workspace = true }

[features]
paranoid = []

[[bench]]
name = "g1_alloc"
harness = false

[lints]
workspace = true
