[package]
name = "lume_hir_lower"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
arc = { workspace = true }
lume_ast = { workspace = true }
lume_errors = { workspace = true }
lume_hir = { workspace = true }
lume_lexer = { workspace = true }
lume_parser = { workspace = true }
lume_session = { workspace = true }
lume_syntax = { workspace = true }
lume_span = { workspace = true }

error_snippet = { workspace = true }
error_snippet_derive = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
lume_errors_test = { workspace = true }
insta = { version = "1.42.2", features = ["yaml"] }

[lints]
workspace = true
