[package]
name = "lume_linker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
test = false
doctest = false

[dependencies]
lume_assets = { workspace = true }
lume_errors = { workspace = true }
lume_session = { workspace = true }

tracing = { workspace = true }

[lints]
workspace = true
