[package]
name = "lume_mir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
test = false
doctest = false

[dependencies]
lume_session = { workspace = true }
lume_span = { workspace = true }
lume_type_metadata = { workspace = true }
lume_types = { workspace = true }

indexmap = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }

[lints]
workspace = true
