[package]
name = "lume_cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
test = false
doctest = false

[dependencies]
arc = { workspace = true }
lume_cli_tools = { workspace = true }
lume_driver = { workspace = true, features = ["codegen"] }
lume_fmt = { workspace = true }
lume_errors = { workspace = true }
lume_errors_derive = { workspace = true }
lume_lsp = { workspace = true, optional = true }
lume_session = { workspace = true }
lume_span = { workspace = true }
lume_tracing = { workspace = true }

askama = { version = "0.15.6" }
clap = { workspace = true }
glob = { version = "^0" }
toml = { version = "0.9.6" }
tracing = { workspace = true }

[features]
default = ["lsp"]
lsp = ["dep:lume_lsp"]

[lints]
workspace = true
