[package]
name = "lume_unification"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
lume_errors = { workspace = true }
lume_errors_derive = { workspace = true }
lume_hash = { workspace = true }
lume_hir = { workspace = true }
lume_infer = { workspace = true }
lume_types = { workspace = true }
lume_session = { workspace = true }
lume_span = { workspace = true }

derive_more = { version = "*", features = ["debug", "eq"] }
indexmap = { workspace = true }
lume_architect = { workspace = true }
smallvec = { version = "^1.15" }
tracing = { workspace = true }

[lints]
workspace = true
