[package]
name = "lume_codegen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
lume_errors = { workspace = true }
lume_hash = { workspace = true }
lume_mir = { workspace = true }
lume_options = { workspace = true }
lume_session = { workspace = true }
lume_span = { workspace = true }
lume_tagged = { workspace = true }
lume_type_metadata = { workspace = true }

gimli = { version = "0.32.3" }
indexmap = { workspace = true }
object = { version = "0.37", features = ["write"] }
target-lexicon = { version = "=0.13.2" }
tracing = { workspace = true }

cranelift = "=0.127.1"
cranelift-codegen = { version = "=0.127.1", features = ["unwind"] }
cranelift-module = "=0.127.1"
cranelift-native = "=0.127.1"
cranelift-object = { version = "=0.127.1" }

[lints]
workspace = true
