[package]
name = "lume_typech"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
lume_errors = { workspace = true }
lume_errors_derive = { workspace = true }
lume_hir = { workspace = true }
lume_infer = { workspace = true }
lume_session = { workspace = true }
lume_span = { workspace = true }
lume_types = { workspace = true }

lume_architect = { workspace = true }
indexmap = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
arc = { workspace = true }
lume_errors_test = { workspace = true }
lume_hir_lower = { workspace = true }

insta = { version = "1.42.2", features = ["yaml"] }

[lints]
workspace = true
